import React from "react";

function Cards() {
  let cards = [
   {
  id: 1,
  title: "Men's Casual Cotton Shirt",
  subtitle: "Men Wear",
  description: "Breathable cotton shirt ideal for daily casual and office wear.",
  image: "https://picsum.photos/400?random=1",
  price: 24.99,
  buttonText: "Learn More",
},
{
  id: 2,
  title: "Women's Floral Summer Dress",
  subtitle: "Women Wear",
  description: "Lightweight floral dress perfect for summer outings.",
  image: "https://picsum.photos/400?random=2",
  price: 29.99,
  buttonText: "Learn More",
},
{
  id: 3,
  title: "Men's Slim Fit Jeans",
  subtitle: "Men Wear",
  description: "Stretchable slim fit jeans for all-day comfort.",
  image: "https://picsum.photos/400?random=3",
  price: 39.99,
  buttonText: "Learn More",
},
{
  id: 4,
  title: "Women's High Waist Jeans",
  subtitle: "Women Wear",
  description: "Trendy high waist jeans with modern fit.",
  image: "https://picsum.photos/400?random=4",
  price: 42.99,
  buttonText: "Learn More",
},
{
  id: 5,
  title: "Unisex Graphic T-Shirt",
  subtitle: "Unisex",
  description: "Premium cotton t-shirt with trendy graphic print.",
  image: "https://picsum.photos/400?random=5",
  price: 14.99,
  buttonText: "Learn More",
},
{
  id: 6,
  title: "Men's Hooded Sweatshirt",
  subtitle: "Men Wear",
  description: "Warm hoodie suitable for winter and casual wear.",
  image: "https://picsum.photos/400?random=6",
  price: 44.99,
  buttonText: "Learn More",
},
{
  id: 7,
  title: "Women's Knitted Sweater",
  subtitle: "Women Wear",
  description: "Soft knitted sweater designed for winter comfort.",
  image: "https://picsum.photos/400?random=7",
  price: 38.99,
  buttonText: "Learn More",
},
{
  id: 8,
  title: "Men's Formal Blazer",
  subtitle: "Men Wear",
  description: "Classic formal blazer for office and events.",
  image: "https://picsum.photos/400?random=8",
  price: 89.99,
  buttonText: "Learn More",
},
{
  id: 9,
  title: "Women's Office Blazer",
  subtitle: "Women Wear",
  description: "Elegant blazer for professional office look.",
  image: "https://picsum.photos/400?random=9",
  price: 84.99,
  buttonText: "Learn More",
},
{
  id: 10,
  title: "Men's Track Pants",
  subtitle: "Men Wear",
  description: "Comfortable track pants for workouts and casual wear.",
  image: "https://picsum.photos/400?random=10",
  price: 26.99,
  buttonText: "Learn More",
},

{
  id: 11,
  title: "Women's Yoga Leggings",
  subtitle: "Women Wear",
  description: "Stretchable yoga leggings with perfect fit.",
  image: "https://picsum.photos/400?random=11",
  price: 22.99,
  buttonText: "Learn More",
},
{
  id: 12,
  title: "Men's Leather Jacket",
  subtitle: "Men Wear",
  description: "Stylish faux leather jacket with premium finish.",
  image: "https://picsum.photos/400?random=12",
  price: 119.99,
  buttonText: "Learn More",
},
{
  id: 13,
  title: "Women's Winter Coat",
  subtitle: "Women Wear",
  description: "Long winter coat offering warmth and elegance.",
  image: "https://picsum.photos/400?random=13",
  price: 129.99,
  buttonText: "Learn More",
},
{
  id: 14,
  title: "Men's Polo T-Shirt",
  subtitle: "Men Wear",
  description: "Classic polo t-shirt made with breathable fabric.",
  image: "https://picsum.photos/400?random=14",
  price: 19.99,
  buttonText: "Learn More",
},
{
  id: 15,
  title: "Women's Crop Top",
  subtitle: "Women Wear",
  description: "Stylish crop top suitable for casual wear.",
  image: "https://picsum.photos/400?random=15",
  price: 16.99,
  buttonText: "Learn More",
},
{
  id: 16,
  title: "Men's Chino Pants",
  subtitle: "Men Wear",
  description: "Comfortable chinos for casual and semi-formal use.",
  image: "https://picsum.photos/400?random=16",
  price: 34.99,
  buttonText: "Learn More",
},
{
  id: 17,
  title: "Women's Palazzo Pants",
  subtitle: "Women Wear",
  description: "Flowy palazzo pants with breathable fabric.",
  image: "https://picsum.photos/400?random=17",
  price: 28.99,
  buttonText: "Learn More",
},
{
  id: 18,
  title: "Men's Printed Hoodie",
  subtitle: "Men Wear",
  description: "Printed hoodie with soft inner lining.",
  image: "https://picsum.photos/400?random=18",
  price: 49.99,
  buttonText: "Learn More",
},
{
  id: 19,
  title: "Women's Cardigan",
  subtitle: "Women Wear",
  description: "Open-front cardigan perfect for layering.",
  image: "https://picsum.photos/400?random=19",
  price: 36.99,
  buttonText: "Learn More",
},
{
  id: 20,
  title: "Men's Formal Trousers",
  subtitle: "Men Wear",
  description: "Tailored trousers ideal for office wear.",
  image: "https://picsum.photos/400?random=20",
  price: 41.99,
  buttonText: "Learn More",
},

{
  id: 21,
  title: "Women's Party Gown",
  subtitle: "Women Wear",
  description: "Elegant gown designed for special occasions.",
  image: "https://picsum.photos/400?random=21",
  price: 149.99,
  buttonText: "Learn More",
},
{
  id: 22,
  title: "Men's Sleeveless Jacket",
  subtitle: "Men Wear",
  description: "Lightweight sleeveless jacket for winter layering.",
  image: "https://picsum.photos/400?random=22",
  price: 54.99,
  buttonText: "Learn More",
},
{
  id: 23,
  title: "Women's Denim Jacket",
  subtitle: "Women Wear",
  description: "Classic denim jacket with modern fit.",
  image: "https://picsum.photos/400?random=23",
  price: 59.99,
  buttonText: "Learn More",
},
{
  id: 24,
  title: "Men's Wool Sweater",
  subtitle: "Men Wear",
  description: "Warm wool sweater for winter comfort.",
  image: "https://picsum.photos/400?random=24",
  price: 47.99,
  buttonText: "Learn More",
},
{
  id: 25,
  title: "Women's Wool Shawl",
  subtitle: "Women Wear",
  description: "Soft wool shawl for winter styling.",
  image: "https://picsum.photos/400?random=25",
  price: 24.99,
  buttonText: "Learn More",
},

{
  id: 26,
  title: "Men's Cargo Pants",
  subtitle: "Men Wear",
  description: "Durable cargo pants with multiple pockets.",
  image: "https://picsum.photos/400?random=26",
  price: 37.99,
  buttonText: "Learn More",
},
{
  id: 27,
  title: "Women's Kurti",
  subtitle: "Women Wear",
  description: "Traditional kurti with modern design.",
  image: "https://picsum.photos/400?random=27",
  price: 29.99,
  buttonText: "Learn More",
},
{
  id: 28,
  title: "Men's Gym Vest",
  subtitle: "Men Wear",
  description: "Breathable vest for workout sessions.",
  image: "https://picsum.photos/400?random=28",
  price: 12.99,
  buttonText: "Learn More",
},
{
  id: 29,
  title: "Women's Sports Bra",
  subtitle: "Women Wear",
  description: "Supportive sports bra for intense workouts.",
  image: "https://picsum.photos/400?random=29",
  price: 21.99,
  buttonText: "Learn More",
},
{
  id: 30,
  title: "Men's Rain Jacket",
  subtitle: "Men Wear",
  description: "Water-resistant jacket for rainy weather.",
  image: "https://picsum.photos/400?random=30",
  price: 64.99,
  buttonText: "Learn More",
},

{
  id: 31,
  title: "Women's Windcheater",
  subtitle: "Women Wear",
  description: "Lightweight windcheater for outdoor use.",
  image: "https://picsum.photos/400?random=31",
  price: 52.99,
  buttonText: "Learn More",
},
{
  id: 32,
  title: "Men's Nightwear Pajamas",
  subtitle: "Men Wear",
  description: "Soft cotton pajamas for comfortable sleep.",
  image: "https://picsum.photos/400?random=32",
  price: 19.99,
  buttonText: "Learn More",
},
{
  id: 33,
  title: "Women's Night Suit",
  subtitle: "Women Wear",
  description: "Comfortable night suit set with soft fabric.",
  image: "https://picsum.photos/400?random=33",
  price: 27.99,
  buttonText: "Learn More",
},
{
  id: 34,
  title: "Men's Wool Scarf",
  subtitle: "Men Wear",
  description: "Warm scarf for winter protection.",
  image: "https://picsum.photos/400?random=34",
  price: 14.99,
  buttonText: "Learn More",
},
{
  id: 35,
  title: "Women's Fashion Shrug",
  subtitle: "Women Wear",
  description: "Stylish shrug to layer your outfit.",
  image: "https://picsum.photos/400?random=35",
  price: 19.99,
  buttonText: "Learn More",
},

{
  id: 36,
  title: "Men's Formal Shirt",
  subtitle: "Men Wear",
  description: "Premium formal shirt for office wear.",
  image: "https://picsum.photos/400?random=36",
  price: 32.99,
  buttonText: "Learn More",
},
{
  id: 37,
  title: "Women's Satin Top",
  subtitle: "Women Wear",
  description: "Elegant satin top with smooth finish.",
  image: "https://picsum.photos/400?random=37",
  price: 26.99,
  buttonText: "Learn More",
},
{
  id: 38,
  title: "Men's Winter Gloves",
  subtitle: "Men Wear",
  description: "Insulated gloves for cold weather.",
  image: "https://picsum.photos/400?random=38",
  price: 11.99,
  buttonText: "Learn More",
},
{
  id: 39,
  title: "Women's Wool Cap",
  subtitle: "Women Wear",
  description: "Warm wool cap for winter season.",
  image: "https://picsum.photos/400?random=39",
  price: 9.99,
  buttonText: "Learn More",
},
{
  id: 40,
  title: "Men's Casual Shorts",
  subtitle: "Men Wear",
  description: "Comfortable shorts for summer wear.",
  image: "https://picsum.photos/400?random=40",
  price: 18.99,
  buttonText: "Learn More",
},

{
  id: 41,
  title: "Women's Summer Skirt",
  subtitle: "Women Wear",
  description: "Lightweight skirt perfect for summer days.",
  image: "https://picsum.photos/400?random=41",
  price: 22.99,
  buttonText: "Learn More",
},
{
  id: 42,
  title: "Men's Thermal Wear Set",
  subtitle: "Men Wear",
  description: "Thermal wear set to keep you warm.",
  image: "https://picsum.photos/400?random=42",
  price: 34.99,
  buttonText: "Learn More",
},
{
  id: 43,
  title: "Women's Thermal Top",
  subtitle: "Women Wear",
  description: "Soft thermal top for winter comfort.",
  image: "https://picsum.photos/400?random=43",
  price: 28.99,
  buttonText: "Learn More",
},
{
  id: 44,
  title: "Men's Casual Jacket",
  subtitle: "Men Wear",
  description: "Everyday casual jacket with modern fit.",
  image: "https://picsum.photos/400?random=44",
  price: 69.99,
  buttonText: "Learn More",
},
{
  id: 45,
  title: "Women's Designer Saree",
  subtitle: "Women Wear",
  description: "Premium designer saree with elegant detailing.",
  image: "https://picsum.photos/400?random=45",
  price: 179.99,
  buttonText: "Learn More",
},

{
  id: 46,
  title: "Men's Ethnic Kurta",
  subtitle: "Men Wear",
  description: "Traditional kurta suitable for festive occasions.",
  image: "https://picsum.photos/400?random=46",
  price: 39.99,
  buttonText: "Learn More",
},
{
  id: 47,
  title: "Women's Anarkali Dress",
  subtitle: "Women Wear",
  description: "Beautiful anarkali dress with ethnic design.",
  image: "https://picsum.photos/400?random=47",
  price: 89.99,
  buttonText: "Learn More",
},
{
  id: 48,
  title: "Men's Nehru Jacket",
  subtitle: "Men Wear",
  description: "Classic Nehru jacket for ethnic wear.",
  image: "https://picsum.photos/400?random=48",
  price: 54.99,
  buttonText: "Learn More",
},
{
  id: 49,
  title: "Women's Dupatta",
  subtitle: "Women Wear",
  description: "Stylish dupatta with soft fabric.",
  image: "https://picsum.photos/400?random=49",
  price: 14.99,
  buttonText: "Learn More",
},
{
  id: 50,
  title: "Men's Wedding Sherwani",
  subtitle: "Men Wear",
  description: "Premium sherwani designed for wedding occasions.",
  image: "https://picsum.photos/400?random=50",
  price: 249.99,
  buttonText: "Learn More",
},

{
  id: 51,
  title: "Women's Lehenga Choli",
  subtitle: "Women Wear",
  description: "Designer lehenga choli for festive wear.",
  image: "https://picsum.photos/400?random=51",
  price: 199.99,
  buttonText: "Learn More",
},
{
  id: 52,
  title: "Men's Casual Kurta",
  subtitle: "Men Wear",
  description: "Casual kurta perfect for daily ethnic wear.",
  image: "https://picsum.photos/400?random=52",
  price: 29.99,
  buttonText: "Learn More",
},
{
  id: 53,
  title: "Women's Straight Kurta",
  subtitle: "Women Wear",
  description: "Comfortable straight kurta for daily use.",
  image: "https://picsum.photos/400?random=53",
  price: 27.99,
  buttonText: "Learn More",
},
{
  id: 54,
  title: "Men's Casual Vest",
  subtitle: "Men Wear",
  description: "Lightweight casual vest for layering.",
  image: "https://picsum.photos/400?random=54",
  price: 17.99,
  buttonText: "Learn More",
},
{
  id: 55,
  title: "Women's Long Skirt",
  subtitle: "Women Wear",
  description: "Flowy long skirt with elegant look.",
  image: "https://picsum.photos/400?random=55",
  price: 31.99,
  buttonText: "Learn More",
},

{
  id: 56,
  title: "Men's Casual Hoodie",
  subtitle: "Men Wear",
  description: "Everyday hoodie with comfortable fabric.",
  image: "https://picsum.photos/400?random=56",
  price: 46.99,
  buttonText: "Learn More",
},
{
  id: 57,
  title: "Women's Casual Hoodie",
  subtitle: "Women Wear",
  description: "Soft hoodie designed for casual outings.",
  image: "https://picsum.photos/400?random=57",
  price: 44.99,
  buttonText: "Learn More",
},
{
  id: 58,
  title: "Men's Denim Jacket",
  subtitle: "Men Wear",
  description: "Classic denim jacket with rugged style.",
  image: "https://picsum.photos/400?random=58",
  price: 74.99,
  buttonText: "Learn More",
},
{
  id: 59,
  title: "Women's Denim Skirt",
  subtitle: "Women Wear",
  description: "Trendy denim skirt with modern cut.",
  image: "https://picsum.photos/400?random=59",
  price: 34.99,
  buttonText: "Learn More",
},
{
  id: 60,
  title: "Unisex Oversized Hoodie",
  subtitle: "Unisex",
  description: "Oversized hoodie for comfort and street style.",
  image: "https://picsum.photos/400?random=60",
  price: 59.99,
  buttonText: "Learn More",
},

  ];
  return (
    <div className="container my-4 br-3">
      <div className="row">
        {cards.map((card) => (
          <div className="col-md-3 mb-4">
            <div className="card" style={{ width: "18rem" }}>
              <img src={card.image} className="card-img-top" alt={card.title} />

              <div className="card-body">
                <h5 className="card-title">{card.title}</h5>
                <h6 className="card-subtitle mb-2 text-muted">
                  {card.subtitle}
                </h6>

                <p className="card-text">{card.description}</p>
                <p className="card-text">{card.price} $</p>

                <a href="#" className="btn btn-primary">
                  {card.buttonText}
                </a>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Cards;
